name: build

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install MPFR
        run: sudo apt install -y libmpfr6 libmpfr-dev
      - name: Build
        uses: threeal/cmake-action@v2.1.0
      - name: Test
        uses: threeal/ctest-action@v1.1.0

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install MPFR
        run: brew install mpfr
      - name: Export homebrew paths
        uses: spezifisch/export-homebrew-build-paths@v1.0.0
      - name: Build
        uses: threeal/cmake-action@v2.1.0
      - name: Test
        uses: threeal/ctest-action@v1.1.0
